import { useMutation, useQueryClient } from '@tanstack/react-query';
import type { HelpTopic } from '@treerepro/contracts';
import { type FormEvent, useId, useState } from 'react';
import { ApiError } from '../../api/client.ts';
import { createHelpTopic, helpKeys, updateHelpTopic } from '../../api/help.ts';
import { fieldErrors, pageErrorMessage } from '../../lib/errors.ts';
import { Alert, Button, Dialog, Field, Input, Textarea } from '../ui/index.ts';

/**
 * Creates a help topic, or edits the title and summary of `topic` (RFC-73
 * R6, R7). The slug is generated by the API and never changes.
 * @rfc RFC-73 R6, R7
 */
export function TopicDialog({
  topic,
  onClose,
  onSaved,
}: {
  topic?: HelpTopic;
  onClose: () => void;
  onSaved: (topic: HelpTopic) => void;
}) {
  const queryClient = useQueryClient();
  const ids = { title: useId(), summary: useId() };
  const [title, setTitle] = useState(topic?.title ?? '');
  const [summary, setSummary] = useState(topic?.summary ?? '');
  const save = useMutation({
    mutationFn: () =>
      topic
        ? updateHelpTopic(topic.id, { title: title.trim(), summary: summary.trim() })
        : createHelpTopic({ title: title.trim(), summary: summary.trim() }),
    onSuccess: async (saved) => {
      await queryClient.invalidateQueries({ queryKey: helpKeys.all });
      onSaved(saved);
    },
  });
  const errors = fieldErrors(save.error);
  const other = save.error && !errors.title && !errors.summary;

  function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    save.mutate();
  }

  return (
    <Dialog
      open
      title={topic ? 'Edit topic' : 'New topic'}
      onClose={onClose}
      closeDisabled={save.isPending}
    >
      <form onSubmit={submit} className="flex flex-col gap-4" noValidate>
        <Field id={ids.title} label="Title" error={errors.title}>
          <Input
            id={ids.title}
            value={title}
            maxLength={200}
            onChange={(e) => setTitle(e.target.value)}
            invalid={Boolean(errors.title)}
          />
        </Field>
        <Field id={ids.summary} label="Summary (optional)" error={errors.summary}>
          <Textarea
            id={ids.summary}
            value={summary}
            maxLength={500}
            rows={2}
            onChange={(e) => setSummary(e.target.value)}
          />
        </Field>
        {other ? (
          <Alert tone="error">
            {save.error instanceof ApiError && save.error.code === 'HELP_SLUG_TAKEN'
              ? 'Another topic already has this title.'
              : pageErrorMessage(save.error)}
          </Alert>
        ) : null}
        <div className="flex justify-end gap-2">
          <Button variant="secondary" onClick={onClose} disabled={save.isPending}>
            Cancel
          </Button>
          <Button type="submit" pending={save.isPending}>
            Save
          </Button>
        </div>
      </form>
    </Dialog>
  );
}
