/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppTraitsRouteImport } from './routes/app/traits'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as ResetPasswordTokenRouteImport } from './routes/reset-password.$token'
import { Route as AppImportsIndexRouteImport } from './routes/app/imports/index'
import { Route as AppImportsIdRouteImport } from './routes/app/imports/$id'
import { Route as AppReferencesIndexRouteImport } from './routes/app/references/index'
import { Route as AppReferencesIdRouteImport } from './routes/app/references/$id'
import { Route as AppSpeciesIndexRouteImport } from './routes/app/species/index'
import { Route as AppSpeciesIdRouteImport } from './routes/app/species/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTraitsRoute = AppTraitsRouteImport.update({
  id: '/traits',
  path: '/traits',
  getParentRoute: () => AppRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordTokenRoute = ResetPasswordTokenRouteImport.update({
  id: '/reset-password/$token',
  path: '/reset-password/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppImportsIndexRoute = AppImportsIndexRouteImport.update({
  id: '/imports/',
  path: '/imports/',
  getParentRoute: () => AppRoute,
} as any)
const AppImportsIdRoute = AppImportsIdRouteImport.update({
  id: '/imports/$id',
  path: '/imports/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppReferencesIndexRoute = AppReferencesIndexRouteImport.update({
  id: '/references/',
  path: '/references/',
  getParentRoute: () => AppRoute,
} as any)
const AppReferencesIdRoute = AppReferencesIdRouteImport.update({
  id: '/references/$id',
  path: '/references/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSpeciesIndexRoute = AppSpeciesIndexRouteImport.update({
  id: '/species/',
  path: '/species/',
  getParentRoute: () => AppRoute,
} as any)
const AppSpeciesIdRoute = AppSpeciesIdRouteImport.update({
  id: '/species/$id',
  path: '/species/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/traits': typeof AppTraitsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/app/': typeof AppIndexRoute
  '/app/imports/$id': typeof AppImportsIdRoute
  '/app/references/$id': typeof AppReferencesIdRoute
  '/app/species/$id': typeof AppSpeciesIdRoute
  '/app/imports/': typeof AppImportsIndexRoute
  '/app/references/': typeof AppReferencesIndexRoute
  '/app/species/': typeof AppSpeciesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/traits': typeof AppTraitsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/app': typeof AppIndexRoute
  '/app/imports/$id': typeof AppImportsIdRoute
  '/app/references/$id': typeof AppReferencesIdRoute
  '/app/species/$id': typeof AppSpeciesIdRoute
  '/app/imports': typeof AppImportsIndexRoute
  '/app/references': typeof AppReferencesIndexRoute
  '/app/species': typeof AppSpeciesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/traits': typeof AppTraitsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/app/': typeof AppIndexRoute
  '/app/imports/$id': typeof AppImportsIdRoute
  '/app/references/$id': typeof AppReferencesIdRoute
  '/app/species/$id': typeof AppSpeciesIdRoute
  '/app/imports/': typeof AppImportsIndexRoute
  '/app/references/': typeof AppReferencesIndexRoute
  '/app/species/': typeof AppSpeciesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/app/settings'
    | '/app/traits'
    | '/invite/$token'
    | '/reset-password/$token'
    | '/app/'
    | '/app/imports/$id'
    | '/app/references/$id'
    | '/app/species/$id'
    | '/app/imports/'
    | '/app/references/'
    | '/app/species/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/app/settings'
    | '/app/traits'
    | '/invite/$token'
    | '/reset-password/$token'
    | '/app'
    | '/app/imports/$id'
    | '/app/references/$id'
    | '/app/species/$id'
    | '/app/imports'
    | '/app/references'
    | '/app/species'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/app/settings'
    | '/app/traits'
    | '/invite/$token'
    | '/reset-password/$token'
    | '/app/'
    | '/app/imports/$id'
    | '/app/references/$id'
    | '/app/species/$id'
    | '/app/imports/'
    | '/app/references/'
    | '/app/species/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ResetPasswordTokenRoute: typeof ResetPasswordTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/traits': {
      id: '/app/traits'
      path: '/traits'
      fullPath: '/app/traits'
      preLoaderRoute: typeof AppTraitsRouteImport
      parentRoute: typeof AppRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/$token': {
      id: '/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/reset-password/$token'
      preLoaderRoute: typeof ResetPasswordTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/imports/': {
      id: '/app/imports/'
      path: '/imports'
      fullPath: '/app/imports/'
      preLoaderRoute: typeof AppImportsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/imports/$id': {
      id: '/app/imports/$id'
      path: '/imports/$id'
      fullPath: '/app/imports/$id'
      preLoaderRoute: typeof AppImportsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/references/': {
      id: '/app/references/'
      path: '/references'
      fullPath: '/app/references/'
      preLoaderRoute: typeof AppReferencesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/references/$id': {
      id: '/app/references/$id'
      path: '/references/$id'
      fullPath: '/app/references/$id'
      preLoaderRoute: typeof AppReferencesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/species/': {
      id: '/app/species/'
      path: '/species'
      fullPath: '/app/species/'
      preLoaderRoute: typeof AppSpeciesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/species/$id': {
      id: '/app/species/$id'
      path: '/species/$id'
      fullPath: '/app/species/$id'
      preLoaderRoute: typeof AppSpeciesIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppSettingsRoute: typeof AppSettingsRoute
  AppTraitsRoute: typeof AppTraitsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppImportsIdRoute: typeof AppImportsIdRoute
  AppReferencesIdRoute: typeof AppReferencesIdRoute
  AppSpeciesIdRoute: typeof AppSpeciesIdRoute
  AppImportsIndexRoute: typeof AppImportsIndexRoute
  AppReferencesIndexRoute: typeof AppReferencesIndexRoute
  AppSpeciesIndexRoute: typeof AppSpeciesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSettingsRoute: AppSettingsRoute,
  AppTraitsRoute: AppTraitsRoute,
  AppIndexRoute: AppIndexRoute,
  AppImportsIdRoute: AppImportsIdRoute,
  AppReferencesIdRoute: AppReferencesIdRoute,
  AppSpeciesIdRoute: AppSpeciesIdRoute,
  AppImportsIndexRoute: AppImportsIndexRoute,
  AppReferencesIndexRoute: AppReferencesIndexRoute,
  AppSpeciesIndexRoute: AppSpeciesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InviteTokenRoute: InviteTokenRoute,
  ResetPasswordTokenRoute: ResetPasswordTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
