/**
 * Error code → HTTP status. Mirrors the catalog table in RFC-12.
 * @rfc RFC-12 R1-R4
 */
export const ERROR_CODES = {
  VALIDATION_FAILED: 400,
  VALIDATION_INVALID_JSON: 400,
  SECURITY_INVALID_ORIGIN: 403,
  NOT_FOUND: 404,
  REQUEST_TOO_LARGE: 413,
  RATE_LIMITED: 429,
  INTERNAL_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
  AUTH_INVALID_CREDENTIALS: 401,
  AUTH_UNAUTHENTICATED: 401,
  AUTH_TOTP_INVALID: 401,
  AUTH_MFA_EXPIRED: 401,
  AUTH_ACCOUNT_SUSPENDED: 403,
  AUTH_TOKEN_INVALID: 400,
  AUTH_PASSWORD_WEAK: 400,
  AUTH_TOTP_ALREADY_ENABLED: 409,
  AUTH_TOTP_NOT_ENABLED: 409,
  USER_EMAIL_TAKEN: 409,
  PERMISSION_DENIED: 403,
  PERMISSION_UNKNOWN: 400,
  ROLE_NOT_FOUND: 404,
  ROLE_NAME_TAKEN: 409,
  ROLE_IS_SYSTEM: 409,
  ROLE_LAST_ADMIN: 409,
  USER_NOT_FOUND: 404,
  USER_INVALID_STATUS: 409,
  MAIL_SEND_FAILED: 502,
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
