import { randomBytes } from 'node:crypto';

export const BASE_URL = process.env.E2E_BASE_URL ?? 'http://localhost:8080';
export const MAILPIT_URL = process.env.E2E_MAILPIT_URL ?? 'http://localhost:8026';
export const ADMIN_EMAIL = process.env.E2E_ADMIN_EMAIL ?? 'admin@e2e.test';
/** `storageState` written by `global-setup.ts`, relative to `apps/e2e` (the suite's cwd); `adminContext()` reads it to start a spec file already signed in. */
export const ADMIN_STATE = 'test-results/admin-state.json';

/** The invitation link `scripts/e2e.sh` read from `seed-admin`; `global-setup.ts` accepts it once before the suite starts. */
export function adminInviteLink(): string {
  const link = process.env.E2E_ADMIN_INVITE_LINK;
  if (!link)
    throw new Error('E2E_ADMIN_INVITE_LINK is not set: run the suite through `pnpm test:e2e`');
  return link;
}

/** Generated by `scripts/e2e.sh` (`openssl rand -hex 16`, RFC-21 shaped) and exported to Playwright; guarded like `adminInviteLink()` since a missing value means the suite is not running through `pnpm test:e2e`. */
export function adminPassword(): string {
  const value = process.env.E2E_ADMIN_PASSWORD;
  if (!value)
    throw new Error('E2E_ADMIN_PASSWORD is not set: run the suite through `pnpm test:e2e`');
  return value;
}

/** A fresh password per call: long enough for RFC-21 and never in a breach list. */
export function password(): string {
  return `Pw-${randomBytes(6).toString('hex')}-Tree!`;
}
